### ISSUE TITLE
Fail to Install Retip

### ISSUE THREAD

**Issue by TalWac** [PaoloBnn/Retip#8]
Dear Retip developer,
I'm haveing issues that could not solve in installing the packge. 

My system :
``> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night
``

I'm  receiving this message: 

``> devtools::install_github("Paolobnn/Retip", force = TRUE)
Downloading GitHub repo Paolobnn/Retip@HEAD
√  checking for file 'C:\Users\BCDD\AppData\Local\Temp\RtmpI7Ny7t\remotesc6984303216d\PaoloBnn-Retip-8c23eda/DESCRIPTION' (461ms)
-  preparing 'Retip': (502ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'Retip_0.5.4.tar.gz' (3.1s)
   
Installing package into ‘D:/BCDD/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'Retip' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ggplot2' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'Retip'
* removing 'D:/BCDD/Documents/R/win-library/3.6/Retip'
Error: Failed to install 'Retip' from GitHub:
  (converted from warning) installation of package ‘C:/Users/BCDD/AppData/Local/Temp/RtmpI7Ny7t/filec6987ea92c6b/Retip_0.5.4.tar.gz’ had non-zero exit status``

Any idea how to solve this? 
(If is there any more info needed please tell me)

Many thanks,
Tal

**Comment by tobigithub** [comment]
Hi,
there are multiple dependencies and I see the first error is from ggplot, not retip per se.
```
Error: (converted from warning) package 'ggplot2' was built under R version 3.6.3
Execution halted
```
So try to use R 3.6.3 (not sure if that is possible). Otherwise I always recommend to install
packages into a new virtual machine or a free microinstance on the cloud, like Azure, Google or AWS. 
Just to make sure your current machine setup is not the source of trouble or is not going to be destroyed
by the DLL hell. See also here, I recently did a step-by-step install and everything worked fine.
[Clean cloud install of retip](https://github.com/PaoloBnn/Retip/issues/5#issuecomment-746816542)
That does not mean there is no possible error in retip, it is just the quickest solution to test and use retip.
Cheers
Tobias

**Comment by TalWac** [comment]
Hi,
Thank you for your reply!
I'm not sure I understand what is a virtual machine and how to install it. 
But I did re-install Java and rJava package, so the former error message is gone now. 

Having this one: 

```
Error: package or namespace load failed for 'Retip':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'D:/BCDD/Documents/R/win-library/4.0/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.
```

Kindly your help I'm quite lost

Many thanks

**Comment by tobigithub** [comment]
Hi,
rJava is tricky (your error), there can be underlying issues with the existing system such as home directories, path settings, dependent libraries, older installs that make it very hard to figure out such problems. The clean install works, I just tested it a while ago on a clean VM. 

- Read this: [Software virtualization in chemistry research.](https://jcheminf.biomedcentral.com/articles/10.1186/1758-2946-1-18)  
- Do this:   [How to install a free virtual machine?](https://www.google.com/search?q=how+to+install+free+windows+Virtual+machine)
- Follow this step-by-step in a clean VM:  


1) Download R-4.0.3 (64 bit only)
https://cran.r-project.org/bin/windows/base/

2) Check JAVA version (or install it) in  command line (CMD)
java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

3) Back in R: install.packages("rJava")
4) library(rJava)
5) .jinit

6) print(.jclassPath())
[1] "C:\\Program Files\\R\\R-4.0.3\\library\\rJava\\java"

7) rj <- .jnew("java/lang/String", "Its me rJava here!"); print(rj)
[1] "Java-Object{Its me rJava here!}"

8) Install R-tools ( rtools40-x86_64.exe ) from
https://cran.rstudio.com/bin/windows/Rtools/

8) Now R and rJava are working, its time to prime retip
9) install.packages("devtools")

10) devtools::install_github("Paolobnn/Retiplib")
* DONE (Retiplib)

11) devtools::install_github("Paolobnn/Retip")
* DONE (Retip)

12) library(keras)
install_keras()
Miniconda[Y]:  (yes)
Installation complete.

13) install.packages("lightgbm", repos = "https://cran.r-project.org")
> library(lightgbm)
Loading required package: R6

14) install.packages("readxl")

15) install.packages("rf")

**Comment by TalWac** [comment]
Thank you for the links! greatly appreciated :)
